---
before:
  hooks:
    - go mod download
    - make clean
    - mkdir build/
builds:
  -
    id: my-build
    main: ./cmd/dataplaneapi/main.go
    binary: ./build/dataplaneapi
    ldflags:
      - -s -w -X main.GitRepo={{.GitURL}} -X main.GitTag={{.Tag}} -X main.GitCommit={{.ShortCommit}} -X main.GitDirty= -X main.BuildTime={{.Date}}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - freebsd
    goarch:
      - 386
      - amd64
      - arm
      - arm64
archives:
  -
    id: my-archive
    builds:
      - my-build
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    replacements:
      linux: Linux
      darwin: Darwin
      freebsd: FreeBSD
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
release:
  draft: true
  name_template: "HAProxy {{toupper .ProjectName}} v{{.Version}}"
